In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report
from keras.models import Sequential
from keras.layers import Dense

In [3]:
dataset = pd.read_csv("sample.csv",names=list(range(1,296)))

In [4]:
dataset.head()

1    2        3    4    5    6    7    8    9    10  ...   286  287  288  \
0    0    0  20000.0    0    0    1    0    0    0    0 ...     0    0    0   
0    0    0   7059.0    0    0    1    0    0    0    0 ...     0    0    0   
0    0    0   3150.0    0    0    1    0    0    0    0 ...     0    0    0   
0    0    0  24000.0    0    0    1    0    0    0    0 ...     0    0    0   
0    0    0   5600.0    0    0    1    0    0    0    0 ...     0    0    0   

   289  290  291  292  293         294  295  
0    0    0    1    0    0  259.227165    B  
0    0    0    0    1    0  271.983584    E  
0    0    0    1    0    0  235.233437    D  
0    0    0    0    1    0  415.104389    C  
0    0    0    0    0    1  462.230610    D  

[5 rows x 295 columns]

In [6]:
dataset.describe()

1             2             3             4             5    \
count  66137.000000  66137.000000  66137.000000  66137.000000  66137.000000   
mean       0.014757      0.003765  11226.207294      0.213511      0.049261   
std        0.120581      0.061244   8153.148240      0.609365      0.216415   
min        0.000000      0.000000     13.000000      0.000000      0.000000   
25%        0.000000      0.000000   4000.000000      0.000000      0.000000   
50%        0.000000      0.000000   9614.800000      0.000000      0.000000   
75%        0.000000      0.000000  18984.000000      0.000000      0.000000   
max        1.000000      1.000000  72360.000000     10.000000      1.000000   

                6             7             8             9             10   \
count  66137.000000  66137.000000  66137.000000  66137.000000  66137.000000   
mean       0.869498      0.030588      0.005867      0.004249      0.003735   
std        0.336857      0.172200      0.076369      0.065044      0.060998   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      0.000000      0.000000      0.000000   
50%        1.000000      0.000000      0.000000      0.000000      0.000000   
75%        1.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

           ...                285           286           287           288  \
count      ...       66137.000000  66137.000000  66137.000000  66137.000000   
mean       ...           0.011522      0.002646      0.007258      0.007031   
std        ...           0.106719      0.051372      0.084883      0.083556   
min        ...           0.000000      0.000000      0.000000      0.000000   
25%        ...           0.000000      0.000000      0.000000      0.000000   
50%        ...           0.000000      0.000000      0.000000      0.000000   
75%        ...           0.000000      0.000000      0.000000      0.000000   
max        ...           1.000000      1.000000      1.000000      1.000000   

                289           290           291           292           293  \
count  66137.000000  66137.000000  66137.000000  66137.000000  66137.000000   
mean       0.002933      0.257269      0.257934      0.179552      0.305245   
std        0.054081      0.437132      0.437501      0.383816      0.460515   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      1.000000      1.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

                294  
count  66137.000000  
mean     454.969820  
std      221.293898  
min       64.525593  
25%      300.863033  
50%      424.698119  
75%      575.044994  
max     2922.908791  

[8 rows x 294 columns]

In [14]:
dataset[dataset.isnull().any(axis=1)]

Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ...]
Index: []

[0 rows x 295 columns]

No Rows with null value

# X will have independent variables and Y will be the dependent or target variable

In [15]:
X=dataset.iloc[:,:-1]
Y=dataset.iloc[:,-1]

In [25]:
Y.value_counts()

C    46882
D     9279
B     6602
E     2507
A      867
Name: 295, dtype: int64

# Encoding the Target variable from string to integer

In [17]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

# Just to begin with, trying to fit a random forest

In [18]:
# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20)

In [19]:
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [20]:
y_pred = classifier.predict(X_test)

In [22]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[   6,   20,  130,   15,    3],
       [   5,  156,  992,  128,    9],
       [   9,  320, 8732,  365,   31],
       [   5,  108, 1410,  272,   27],
       [   1,   43,  342,   75,   24]])

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           A       0.23      0.03      0.06       174
           B       0.24      0.12      0.16      1290
           C       0.75      0.92      0.83      9457
           D       0.32      0.15      0.20      1822
           E       0.26      0.05      0.08       485

   micro avg       0.69      0.69      0.69     13228
   macro avg       0.36      0.26      0.27     13228
weighted avg       0.62      0.69      0.64     13228



### Precision and Recall are not that great. Probably required to remove some dimensions

#### Checking for correlation

In [27]:
dcorr=X.corr()

In [28]:
dcorr=dcorr.abs()
dcun=dcorr.unstack()
dcunsort=dcun.sort_values(kind="quicksort")

In [31]:
dcunsort

144  185    1.453386e-08
185  144    1.453386e-08
166  249    5.926615e-08
249  166    5.926615e-08
244  117    1.003557e-06
117  244    1.003557e-06
292  175    1.635319e-06
175  292    1.635319e-06
35   133    1.743414e-06
133  35     1.743414e-06
36   153    2.465893e-06
153  36     2.465893e-06
162  247    2.832268e-06
247  162    2.832268e-06
96   194    4.113680e-06
194  96     4.113680e-06
286  196    4.664316e-06
196  286    4.664316e-06
55   149    5.493499e-06
149  55     5.493499e-06
86   238    5.917587e-06
238  86     5.917587e-06
252  92     5.940637e-06
92   252    5.940637e-06
55   82     6.779026e-06
82   55     6.779026e-06
196  154    6.981268e-06
154  196    6.981268e-06
148  182    7.446077e-06
182  148    7.446077e-06
                ...     
292  269             NaN
     270             NaN
     271             NaN
     272             NaN
     273             NaN
     274             NaN
     275             NaN
     276             NaN
293  59              NaN


## Not much correlation. Lets try to remove dimensions which has low variance 

In [32]:
from sklearn.feature_selection import VarianceThreshold

In [35]:
columns=X.columns
selector=VarianceThreshold(.8)
selector.fit_transform(X)
features = [columns[x] for x in selector.get_support(indices=True) if x]
new_X = pd.DataFrame(selector.transform(X),columns=features)
new_X

3       36     43        64           294
0      20000.0     1.0  13.60   232.000   259.227165
1       7059.0     0.0   0.40   136.000   271.983584
2       3150.0     1.0   4.40   327.000   235.233437
3      24000.0     1.0  13.60   356.000   415.104389
4       5600.0  2229.0   5.60   710.000   462.230610
5      16507.0     4.0  11.20   779.000   824.520326
6       9329.0     1.0  14.00   430.000   559.273602
7      24000.0     1.0  13.60   304.000   312.010930
8      17000.0     0.0  13.60   468.203   645.829800
9       2400.0     3.0   6.00   430.000   395.571032
10     25000.0     2.0  13.60   273.000   292.129951
11      7485.0     0.0   6.40   332.000   293.810666
12      7884.0     1.0  11.20   404.000   506.651441
13      1300.0     3.0   4.00   484.000   292.485475
14     13506.0     1.0  13.00   499.000   517.928701
15      5000.0     1.0   7.00   528.000   446.867300
16     11432.0     1.0   8.40   419.000   418.975922
17      5979.0     1.0  13.60   522.000   530.264923
18      8800.0     1.0   6.00   483.000   361.724558
19      3000.0     1.0   6.60   697.000   598.069814
20     17019.0     1.0  13.20   587.000   705.463939
21     15000.0     1.0  13.60   630.000   313.409217
22     23800.0     1.0   6.80   184.000   223.444242
23       300.0     0.0   6.00   349.000   279.676798
24      5000.0     1.0   7.00   523.000   774.044890
25      8180.0     1.0  13.60   472.000   512.445656
26     17245.0     1.0   6.80   602.000   619.204610
27      2800.0     3.0   1.60   323.000   256.474298
28      5000.0     1.0   7.00   412.000   328.216951
29     25191.0     1.0  10.40   406.000   475.067674
...        ...     ...    ...       ...          ...
66107  10000.0     1.0  14.00   752.805   900.611737
66108  15000.0     1.0   8.00   557.000   495.459710
66109   5248.0     1.0  11.00   195.000   466.793022
66110  20395.0     3.0  13.60   467.000   444.429227
66111  20500.0     1.0  13.60   439.000   494.169427
66112   5825.0     0.0  11.20   177.681   125.648648
66113  20000.0     3.0  11.20   540.000   570.985755
66114  24000.0     1.0  13.60   566.000   609.870164
66115   5000.0     0.0   8.50   151.000   206.658514
66116   6251.0     3.0  15.60   460.000   526.830406
66117  23424.0     1.0  13.60   431.000   493.146667
66118   2800.0     1.0  13.60   826.000  1075.850163
66119   4239.0     1.0   2.00  1882.593  1933.548156
66120  24000.0     3.0  13.60   312.000   384.472253
66121   3700.0     1.0  13.20   666.000   690.726321
66122  18000.0     1.0  10.00   588.000   576.028677
66123   2800.0     5.0   3.65  1193.000   569.665265
66124   6000.0     1.0  11.60   817.733   844.079090
66125   5985.0     1.0   9.50   238.000   349.282231
66126   4588.0     1.0  13.60   322.000   360.819032
66127  11486.0     0.0   7.20   339.000   335.297825
66128   2627.0     0.0   5.20   216.000   261.188227
66129  17357.0     0.0  13.60   233.000   350.250564
66130   7763.0     3.0  13.00   631.000   660.428712
66131  18000.0     3.0  13.60   858.000   874.345761
66132   5000.0     1.0  10.00   720.361   754.125582
66133  13759.0     1.0  10.00   501.000   521.998666
66134  12100.0     1.0  10.40   304.000   430.970745
66135  17280.0     3.0   6.40   612.000   588.470479
66136   1047.0     0.0   1.60   421.427   377.895620

[66137 rows x 5 columns]

In [36]:
scaler = StandardScaler()
scaler.fit(new_X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [41]:
X_scaled=scaler.transform(new_X)
type(X_scaled)

numpy.ndarray

In [42]:
# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, test_size = 0.20)
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [43]:
y_pred = classifier.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           A       0.19      0.04      0.07       204
           B       0.24      0.15      0.18      1313
           C       0.75      0.90      0.82      9359
           D       0.30      0.16      0.21      1876
           E       0.23      0.07      0.10       476

   micro avg       0.68      0.68      0.68     13228
   macro avg       0.34      0.26      0.28     13228
weighted avg       0.61      0.68      0.63     13228



In [44]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, encoded_Y, test_size = 0.20)

In [46]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [47]:
predictions = mlp.predict(X_test)

In [48]:
print(confusion_matrix(y_test,predictions))

print(classification_report(y_test,predictions))

[[   0    2  158    2    0]
 [   1    3 1270   10    0]
 [   0    3 9381   33    0]
 [   2    1 1877   21    0]
 [   0    0  446   18    0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       162
           1       0.33      0.00      0.00      1284
           2       0.71      1.00      0.83      9417
           3       0.25      0.01      0.02      1901
           4       0.00      0.00      0.00       464

   micro avg       0.71      0.71      0.71     13228
   macro avg       0.26      0.20      0.17     13228
weighted avg       0.58      0.71      0.60     13228



/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [64]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

In [73]:
encoded_Y=np_utils.to_categorical(encoded_Y)

In [74]:
from keras.utils import np_utils
#encoded_Y = np_utils.to_categorical(encoded_Y)
#X_scaled=scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, encoded_Y, test_size = 0.20)

In [75]:

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 10, activation = 'relu', input_dim = 5))

classifier.add(Dense(output_dim = 5, activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)



/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=5, units=10)`
  
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=5)`
  
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
52909/52909 [==============================] - 18s 333us/step - loss: 0.3112 - acc: 0.8783
Epoch 2/100
52909/52909 [==============================] - 16s 309us/step - loss: 0.2961 - acc: 0.8835
Epoch 3/100
52909/52909 [==============================] - 18s 340us/step - loss: 0.2947 - acc: 0.8836
Epoch 4/100
52909/52909 [==============================] - 20s 374us/step - loss: 0.2939 - acc: 0.8835
Epoch 5/100
52909/52909 [==============================] - 19s 363us/step - loss: 0.2934 - acc: 0.8837
Epoch 6/100
52909/52909 [==============================] - 21s 388us/step - loss: 0.2928 - acc: 0.8839
Epoch 7/100
52909/52909 [==============================] - 20s 370us/step - loss: 0.2925 - acc: 0.8839
Epoch 8/100
52909/52909 [==============================] - 17s 322us/step - loss: 0.2922 - acc: 0.8839
Epoch 9/100
52909/52909 [==============================] - 17s 322us/step - loss: 0.2918 - acc: 0.8842
Epoch 10/100
52909/52909 [==============================] - 17s 314us/ste

52909/52909 [==============================] - 16s 296us/step - loss: 0.2894 - acc: 0.8851
Epoch 80/100
52909/52909 [==============================] - 16s 295us/step - loss: 0.2895 - acc: 0.8851
Epoch 81/100
52909/52909 [==============================] - 16s 294us/step - loss: 0.2895 - acc: 0.8850
Epoch 82/100
52909/52909 [==============================] - 16s 295us/step - loss: 0.2895 - acc: 0.8851
Epoch 83/100
52909/52909 [==============================] - 16s 295us/step - loss: 0.2896 - acc: 0.8847
Epoch 84/100
52909/52909 [==============================] - 16s 295us/step - loss: 0.2895 - acc: 0.8849
Epoch 85/100
52909/52909 [==============================] - 16s 295us/step - loss: 0.2895 - acc: 0.8848
Epoch 86/100
52909/52909 [==============================] - 16s 294us/step - loss: 0.2895 - acc: 0.8849
Epoch 87/100
52909/52909 [==============================] - 16s 295us/step - loss: 0.2894 - acc: 0.8853
Epoch 88/100
52909/52909 [==============================] - 16s 296us/step - 

In [96]:
y_pred = classifier.predict(X_test)


In [97]:
y_pred[y_pred]
#y_pred

array([[8.4134255e-04, 1.7082270e-02, 9.1010785e-01, 6.2599808e-02,
        9.3687242e-03],
       [6.1466955e-03, 8.8736176e-02, 7.8835803e-01, 9.9092431e-02,
        1.7666683e-02],
       [1.8978361e-03, 3.3569016e-02, 8.9678258e-01, 5.9228007e-02,
        8.5225822e-03],
       ...,
       [6.5759257e-03, 9.1104388e-02, 8.0896538e-01, 8.0924124e-02,
        1.2430169e-02],
       [3.3011676e-03, 6.1633170e-02, 8.3915067e-01, 8.0783069e-02,
        1.5131953e-02],
       [3.3770117e-03, 6.1976131e-02, 8.0148864e-01, 1.1230380e-01,
        2.0854378e-02]], dtype=float32)

In [101]:
print(classification_report(y_classes,y_pred))

              precision    recall  f1-score   support

           0       0.50      0.01      0.01       193
           1       0.00      0.00      0.00      1316
           2       0.71      1.00      0.83      9351
           3       0.46      0.01      0.01      1876
           4       0.00      0.00      0.00       492

   micro avg       0.71      0.71      0.71     13228
   macro avg       0.33      0.20      0.17     13228
weighted avg       0.57      0.71      0.59     13228



In [89]:
y_classes = pd.Series([np.argmax(y, axis=None, out=None) for y in y_test])

In [100]:
y_pred=np.argmax(y_pred, axis=1)