In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [109]:
dataset = pd.read_csv("coding_challenge/sample.csv",header=None,names=list(range(1,296)))

In [135]:
#print(dataset.head())
#print(dataset.tail())
dataset.iloc[25,25]=np.NaN
dataset=dataset.iloc[:,:-1]
dataset[dataset.isnull().any(axis=1)]



1    2       3    4    5    6    7    8    9    10  ...   286  287  288  \
0    0    0  8180.0    0    0    1    0    0    0    0 ...     0    0    0   

   289  290  291  292  293         294  295  
0    0    0    0    0    1  512.445656    C  

[1 rows x 295 columns]

In [111]:
dataset.shape

(66137, 295)

In [112]:
X=dataset.iloc[:,:-1]
Y=dataset.iloc[:,-1]

In [122]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
#dummy_y = np_utils.to_categorical(encoded_Y)
pd.Series(encoded_Y).value_counts()


2    46882
3     9279
1     6602
4     2507
0      867
dtype: int64

In [124]:
from sklearn.preprocessing import LabelBinarizer

binencoder = LabelBinarizer()
binencoded_Y = binencoder.fit_transform(Y)
binencoded_Y.shape

(66137, 5)

In [17]:
dataset.describe()

1             2             3             4             5    \
count  66137.000000  66137.000000  66137.000000  66137.000000  66137.000000   
mean       0.014757      0.003765  11226.207294      0.213511      0.049261   
std        0.120581      0.061244   8153.148240      0.609365      0.216415   
min        0.000000      0.000000     13.000000      0.000000      0.000000   
25%        0.000000      0.000000   4000.000000      0.000000      0.000000   
50%        0.000000      0.000000   9614.800000      0.000000      0.000000   
75%        0.000000      0.000000  18984.000000      0.000000      0.000000   
max        1.000000      1.000000  72360.000000     10.000000      1.000000   

                6             7             8             9             10   \
count  66137.000000  66137.000000  66137.000000  66137.000000  66137.000000   
mean       0.869498      0.030588      0.005867      0.004249      0.003735   
std        0.336857      0.172200      0.076369      0.065044      0.060998   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      0.000000      0.000000      0.000000   
50%        1.000000      0.000000      0.000000      0.000000      0.000000   
75%        1.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

           ...                285           286           287           288  \
count      ...       66137.000000  66137.000000  66137.000000  66137.000000   
mean       ...           0.011522      0.002646      0.007258      0.007031   
std        ...           0.106719      0.051372      0.084883      0.083556   
min        ...           0.000000      0.000000      0.000000      0.000000   
25%        ...           0.000000      0.000000      0.000000      0.000000   
50%        ...           0.000000      0.000000      0.000000      0.000000   
75%        ...           0.000000      0.000000      0.000000      0.000000   
max        ...           1.000000      1.000000      1.000000      1.000000   

                289           290           291           292           293  \
count  66137.000000  66137.000000  66137.000000  66137.000000  66137.000000   
mean       0.002933      0.257269      0.257934      0.179552      0.305245   
std        0.054081      0.437132      0.437501      0.383816      0.460515   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      1.000000      1.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

                294  
count  66137.000000  
mean     454.969820  
std      221.293898  
min       64.525593  
25%      300.863033  
50%      424.698119  
75%      575.044994  
max     2922.908791  

[8 rows x 294 columns]

In [19]:
dcorr=dataset.corr()

In [31]:
high_corr_var=np.where(dcorr>0.8)
high_corr_var=[(dcorr.index[x],dcorr.columns[y]) for x,y in zip(*high_corr_var) if x!=y and x<y]

In [32]:
high_corr_var

[(4, 44)]

In [36]:
dcorr.iloc[4,44]

-0.040340717140557474

In [37]:
from sklearn import decomposition

In [45]:
pca = decomposition.PCA(n_components=2)
pca.fit(dataset.iloc[:,:-1])

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [46]:
X=pca.transform(dataset.iloc[:,:-1])

In [47]:
X

array([[  8766.73517775,   -309.03840668],
       [ -4169.33581009,     32.16385738],
       [ -8076.97719102,    136.55335908],
       ...,
       [   871.13325645,   -100.18496006],
       [  6050.65504582,   -235.20283878],
       [-10178.02407469,    191.12254079]])

In [48]:
from sklearn.neural_network import MLPClassifier

In [49]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

In [50]:
from sklearn.preprocessing import LabelEncoder


In [51]:
labelencoder_X_1 = LabelEncoder()


In [55]:
dataset.iloc[:,-1] = labelencoder_X_1.fit_transform(dataset.iloc[:,-1])

In [56]:
Y=dataset.iloc[:,-1]

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [63]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu', input_dim = 2))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=2, units=4, kernel_initializer="uniform")`
  if __name__ == '__main__':
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if sys.path[0] == '':
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  from ipykernel import kernelapp as app
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/100
52909/52909 [==============================] - 20s 387us/step - loss: -16.9517 - acc: 0.0998
Epoch 2/100
52909/52909 [==============================] - 27s 506us/step - loss: -17.3682 - acc: 0.1000
Epoch 3/100
52909/52909 [==============================] - 24s 449us/step - loss: -17.3682 - acc: 0.1000
Epoch 4/100
52909/52909 [==============================] - 21s 402us/step - loss: -17.3682 - acc: 0.1000
Epoch 5/100
52909/52909 [==============================] - 21s 392us/step - loss: -17.3682 - acc: 0.1000
Epoch 6/100
52909/52909 [==============================] - 19s 366us/step - loss: -17.3682 - acc: 0.1000
Epoch 7/100
52909/52909 [==============================] - 18s 344us/step - loss: -17.3682 - acc: 0.1000
Epoch 8/100
52909/52909 [==============================] - 19s 361us/step - loss: -17.3682 - acc: 0.1000
Epoch 9/100
52909/52909 [==============================] - 19s 352us/step - loss: -17.3682 - acc: 0.1000
Epoch 10/100
52909/52909 [=============================

52909/52909 [==============================] - 17s 328us/step - loss: -17.3682 - acc: 0.1000
Epoch 79/100
52909/52909 [==============================] - 17s 327us/step - loss: -17.3682 - acc: 0.1000
Epoch 80/100
52909/52909 [==============================] - 18s 331us/step - loss: -17.3682 - acc: 0.1000
Epoch 81/100
52909/52909 [==============================] - 18s 331us/step - loss: -17.3682 - acc: 0.1000
Epoch 82/100
52909/52909 [==============================] - 17s 327us/step - loss: -17.3682 - acc: 0.1000
Epoch 83/100
52909/52909 [==============================] - 17s 328us/step - loss: -17.3682 - acc: 0.1000
Epoch 84/100
52909/52909 [==============================] - 17s 330us/step - loss: -17.3682 - acc: 0.1000
Epoch 85/100
52909/52909 [==============================] - 17s 327us/step - loss: -17.3682 - acc: 0.1000
Epoch 86/100
52909/52909 [==============================] - 17s 329us/step - loss: -17.3682 - acc: 0.1000
Epoch 87/100
52909/52909 [==============================] -

In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/Users/ajaysingh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [93]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [105]:
Y

(49602, 294)

In [102]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[    6,    35,   139,    25,     2],
       [   12,   211,  1252,   148,    13],
       [   14,   386, 10854,   452,    40],
       [    5,   151,  1811,   342,    25],
       [    2,    60,   433,    79,    38]])

In [106]:
y_test.value_counts()

2    11746
3     2334
1     1636
4      612
0      207
Name: 295, dtype: int64

In [72]:
y_pred = classifier.predict(X_test)

In [75]:
y_pred.shape

(13228, 1)

In [76]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [77]:
y_pred = classifier.predict(X_test)

In [79]:
cm = confusion_matrix(Y_test, y_pred)
cm

array([[   3,   24,  111,   15,    6],
       [  15,  149,  947,  158,   43],
       [  72,  675, 7686,  793,  172],
       [  26,  176, 1313,  291,   57],
       [  12,   64,  321,   69,   30]])

In [83]:
Y_test.value_counts()

2    9398
3    1863
1    1312
4     496
0     159
Name: 295, dtype: int64

In [89]:
X_test

array([[-1726.61670089,   -31.45309453],
       [-8234.16800849,   142.69639781],
       [-5226.95513506,    63.15336384],
       ...,
       [ 2095.90175357,  -132.56973883],
       [-8225.85047457,   142.48451033],
       [12765.79346431,  -414.83787791]])